import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Ninja (M5).
 *
 * Los defaults son los de games-guide/M5-NINJA.md. "Velocidad mínima del
 * corte" va primero del grupo Corte porque es el número que decide si el juego
 * se siente justo: sin él, la estrategia óptima es dejar el dedo quieto.
 */
export const ninjaSettings: SettingsSchema = [
  /* --- Corte --------------------------------------------------------- */
  {
    key: "minSliceSpeed",
    kind: "number",
    label: "Velocidad mínima del corte",
    help: "Debajo de esto el trazo no corta. En 0, apoyar el dedo quieto se vuelve la mejor jugada.",
    group: "Corte",
    min: 0,
    max: 900,
    step: 25,
    unit: "px/s",
    default: 300,
  },
  {
    key: "lives",
    kind: "number",
    label: "Vidas",
    help: "Se pierde una por cada fruta que cae sin cortar. Las bombas que caen solas no cuestan.",
    group: "Corte",
    min: 1,
    max: 9,
    step: 1,
    default: 3,
  },

  /* --- Frutas -------------------------------------------------------- */
  {
    key: "gravity",
    kind: "number",
    label: "Gravedad",
    help: "Parábola simple, sin motor de física. Más gravedad, menos tiempo en el aire.",
    group: "Frutas",
    min: 500,
    max: 1800,
    step: 25,
    unit: "px/s²",
    default: 900,
  },
  {
    key: "launchSpeedMin",
    kind: "number",
    label: "Impulso mínimo",
    group: "Frutas",
    min: 400,
    max: 1200,
    step: 20,
    unit: "px/s",
    default: 760,
  },
  {
    key: "launchSpeedMax",
    kind: "number",
    label: "Impulso máximo",
    help: "Contra 900 de gravedad, 980 px/s deja la fruta poco más de dos segundos en el aire.",
    group: "Frutas",
    min: 500,
    max: 1500,
    step: 20,
    unit: "px/s",
    default: 980,
  },
  {
    key: "fruitRadiusMin",
    kind: "number",
    label: "Radio mínimo",
    group: "Frutas",
    min: 14,
    max: 50,
    step: 1,
    unit: "px",
    default: 26,
  },
  {
    key: "fruitRadiusMax",
    kind: "number",
    label: "Radio máximo",
    group: "Frutas",
    min: 18,
    max: 70,
    step: 1,
    unit: "px",
    default: 38,
  },

  /* --- Tandas -------------------------------------------------------- */
  {
    key: "waveMinDelay",
    kind: "number",
    label: "Espera mínima entre tandas",
    group: "Tandas",
    min: 0.3,
    max: 4,
    step: 0.1,
    unit: "s",
    default: 1.2,
  },
  {
    key: "waveMaxDelay",
    kind: "number",
    label: "Espera máxima entre tandas",
    help: "El intervalo irregular es lo que evita que el juego se vuelva un metrónomo.",
    group: "Tandas",
    min: 0.5,
    max: 6,
    step: 0.1,
    unit: "s",
    default: 2.5,
  },
  {
    key: "waveMinCount",
    kind: "number",
    label: "Frutas mínimas por tanda",
    group: "Tandas",
    min: 1,
    max: 6,
    step: 1,
    default: 1,
  },
  {
    key: "waveMaxCount",
    kind: "number",
    label: "Frutas máximas por tanda",
    help: "Arriba de 6 no entran en pantalla y la partida se vuelve injusta.",
    group: "Tandas",
    min: 1,
    max: 8,
    step: 1,
    default: 5,
  },

  /* --- Bombas -------------------------------------------------------- */
  {
    key: "bombFromPoints",
    kind: "number",
    label: "Bombas desde",
    help: "Puntaje a partir del cual pueden aparecer. Antes, la partida es sólo aprender a cortar.",
    group: "Bombas",
    min: 0,
    max: 3000,
    step: 50,
    unit: "puntos",
    default: 300,
  },
  {
    key: "bombMaxChance",
    kind: "number",
    label: "Probabilidad máxima de bomba",
    help: "Techo por fruta. 17 % es aproximadamente una de cada seis.",
    group: "Bombas",
    min: 0,
    max: 40,
    step: 1,
    unit: "%",
    default: 17,
  },
  {
    key: "bombRamp",
    kind: "number",
    label: "Puntos hasta el techo",
    help: "Cuánto tarda la probabilidad en llegar a su máximo.",
    group: "Bombas",
    min: 100,
    max: 5000,
    step: 100,
    unit: "puntos",
    default: 900,
  },

  /* --- Puntaje ------------------------------------------------------- */
  {
    key: "pointsPerFruit",
    kind: "number",
    label: "Puntos por fruta",
    group: "Puntaje",
    min: 10,
    max: 200,
    step: 10,
    default: 50,
  },
  {
    key: "comboMin",
    kind: "number",
    label: "Frutas para que haya combo",
    help: "Cortar menos que esto en un trazo no paga combo.",
    group: "Puntaje",
    min: 2,
    max: 6,
    step: 1,
    default: 3,
  },
  {
    key: "comboPerFruit",
    kind: "number",
    label: "Combo por fruta del trazo",
    help: "Es lo que hace que valga esperar a que se junten tres en vez de cortar de a una.",
    group: "Puntaje",
    min: 0,
    max: 120,
    step: 5,
    default: 30,
  },
  {
    key: "streakLength",
    kind: "number",
    label: "Largo de la racha",
    help: "Cortes seguidos sin dejar caer una fruta para cobrar el bono.",
    group: "Puntaje",
    min: 3,
    max: 30,
    step: 1,
    default: 10,
  },
  {
    key: "streakBonus",
    kind: "number",
    label: "Bono de racha",
    group: "Puntaje",
    min: 0,
    max: 600,
    step: 25,
    default: 200,
  },
];
