import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Tetris duelo.
 *
 * Los defaults son los de games-guide/R6-TETRIS-DUELO.md y NO son decorativos:
 * los seis numeros de arriba (gravedad, DAS, ARR, retardo de fijado, reinicios
 * y ventana de compensacion) son literalmente lo que separa un Tetris que se
 * siente bien de uno que no. Se dejan tocables porque son lo primero que se
 * quiere probar en una sala, no porque de lo mismo el valor que tengan.
 */
export const tetrisDueloSettings: SettingsSchema = [
  {
    kind: "number",
    key: "gravityMs",
    label: "Gravedad inicial",
    group: "Caída",
    unit: "ms/celda",
    min: 200,
    max: 1600,
    step: 50,
    default: 800,
    help: "Cuánto tarda la pieza en bajar una celda al empezar.",
  },
  {
    kind: "number",
    key: "gravityFactor",
    label: "Aceleración por nivel",
    group: "Caída",
    unit: "%",
    min: 70,
    max: 100,
    step: 1,
    default: 92,
    help: "La gravedad se multiplica por esto cada 10 líneas propias. En 100 % nunca acelera.",
  },
  {
    kind: "number",
    key: "linesPerLevel",
    label: "Líneas por nivel",
    group: "Caída",
    min: 5,
    max: 20,
    step: 1,
    default: 10,
    help: "Cada tanto de líneas sube el nivel: acelera la caída y multiplica los puntos.",
  },
  {
    kind: "number",
    key: "softDropFactor",
    label: "Caída suave",
    group: "Caída",
    unit: "×",
    min: 4,
    max: 40,
    step: 1,
    default: 20,
    help: "Cuántas veces más rápido baja mientras se mantiene ▼. Suma 1 punto por celda.",
  },

  {
    kind: "number",
    key: "dasMs",
    label: "DAS · retardo antes de repetir",
    group: "Repetición",
    unit: "ms",
    min: 60,
    max: 300,
    step: 5,
    default: 130,
    help: "Cuánto hay que mantener el costado antes de que empiece a repetir. Lo calcula el host, no el teléfono.",
  },
  {
    kind: "number",
    key: "arrMs",
    label: "ARR · repetición",
    group: "Repetición",
    unit: "ms",
    min: 10,
    max: 120,
    step: 5,
    default: 30,
    help: "Cada cuánto se mueve una celda mientras seguís apretando. Sin esto hay que tocar 8 veces para cruzar.",
  },

  {
    kind: "number",
    key: "lockDelayMs",
    label: "Retardo de fijado",
    group: "Fijado",
    unit: "ms",
    min: 100,
    max: 1000,
    step: 50,
    default: 500,
    help: "Al apoyarse, la pieza todavía se puede deslizar este tiempo. Es lo que permite el encaje del último momento.",
  },
  {
    kind: "number",
    key: "maxLockResets",
    label: "Reinicios del fijado",
    group: "Fijado",
    min: 0,
    max: 30,
    step: 1,
    default: 15,
    help: "Cuántas veces un movimiento o una rotación reinicia el contador. Sin tope se puede eternizar una pieza.",
  },
  {
    kind: "number",
    key: "clearDelayMs",
    label: "Colapso de líneas",
    group: "Fijado",
    unit: "ms",
    min: 0,
    max: 500,
    step: 20,
    default: 180,
    help: "Lo que dura el aplastado antes de que las filas caigan. Se conserva con movimiento reducido: comunica la mecánica.",
  },

  {
    kind: "number",
    key: "garbageDouble",
    label: "Basura por doble",
    group: "Basura",
    unit: "filas",
    min: 0,
    max: 4,
    step: 1,
    default: 1,
    help: "Un simple no manda nada: es la regla que hace que convenga aguantar.",
  },
  {
    kind: "number",
    key: "garbageTriple",
    label: "Basura por triple",
    group: "Basura",
    unit: "filas",
    min: 0,
    max: 6,
    step: 1,
    default: 2,
  },
  {
    kind: "number",
    key: "garbageTetris",
    label: "Basura por tetris",
    group: "Basura",
    unit: "filas",
    min: 1,
    max: 8,
    step: 1,
    default: 4,
    help: "Cuatro líneas de una. Es el golpe que decide los duelos.",
  },
  {
    kind: "number",
    key: "comboBonus",
    label: "Bono por doble seguido",
    group: "Basura",
    unit: "filas",
    min: 0,
    max: 3,
    step: 1,
    default: 1,
    help: "Se suma cuando la pieza anterior también hizo líneas.",
  },
  {
    kind: "number",
    key: "garbageWindowMs",
    label: "Ventana de compensación",
    group: "Basura",
    unit: "ms",
    min: 0,
    max: 3000,
    step: 100,
    default: 1000,
    help: "Entre el envío y la aparición. Lo que completás en ese lapso cancela basura entrante: sin esto no hay remontadas.",
  },

  {
    kind: "number",
    key: "pointsSingle",
    label: "Puntos por línea simple",
    group: "Puntos",
    min: 0,
    max: 400,
    step: 20,
    default: 100,
    help: "Se multiplica por el nivel.",
  },
  {
    kind: "number",
    key: "pointsDouble",
    label: "Puntos por doble",
    group: "Puntos",
    min: 0,
    max: 900,
    step: 20,
    default: 300,
  },
  {
    kind: "number",
    key: "pointsTriple",
    label: "Puntos por triple",
    group: "Puntos",
    min: 0,
    max: 1400,
    step: 20,
    default: 500,
  },
  {
    kind: "number",
    key: "pointsTetris",
    label: "Puntos por tetris",
    group: "Puntos",
    min: 0,
    max: 2000,
    step: 20,
    default: 800,
  },
  {
    kind: "number",
    key: "pointsPerGarbage",
    label: "Puntos por fila enviada",
    group: "Puntos",
    min: 0,
    max: 200,
    step: 10,
    default: 60,
    help: "Premia atacar, no sólo sobrevivir.",
  },
  {
    kind: "number",
    key: "pointsWin",
    label: "Puntos por ganar",
    group: "Puntos",
    min: 0,
    max: 2000,
    step: 50,
    default: 600,
  },

  {
    kind: "number",
    key: "graceSeconds",
    label: "Gracia por desconexión",
    group: "Partida",
    unit: "s",
    min: 5,
    max: 90,
    step: 5,
    default: 30,
    help: "La partida se pausa y la pieza queda flotando. Si no vuelve, el otro gana por abandono.",
  },
];
