import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Vuelo (M3).
 *
 * Flappy vive o muere en tres numeros: gravedad, impulso y separacion de los
 * tubos. Estan primeros y en un grupo propio porque son los que se tocan en
 * vivo, entre dos partidas, hasta que la sensacion cierra.
 */
export const flappySettings: SettingsSchema = [
  /* --- Vuelo --------------------------------------------------------- */
  {
    key: "gravity",
    kind: "number",
    label: "Gravedad",
    help: "Cuanto tira hacia abajo. Más gravedad, caída más pesada y menos margen.",
    group: "Vuelo",
    min: 800,
    max: 3200,
    step: 50,
    unit: "px/s²",
    default: 1800,
  },
  {
    key: "flapImpulse",
    kind: "number",
    label: "Impulso del aleteo",
    help: "Velocidad hacia arriba de cada toque. Contra 1800 de gravedad, 520 da 0,29 s de subida.",
    group: "Vuelo",
    min: 200,
    max: 900,
    step: 10,
    unit: "px/s",
    default: 520,
  },
  {
    key: "maxFallSpeed",
    kind: "number",
    label: "Caída máxima",
    help: "Techo de la velocidad de caída: sin esto la nave se vuelve impredecible al hundirse.",
    group: "Vuelo",
    min: 300,
    max: 1400,
    step: 20,
    unit: "px/s",
    default: 780,
  },
  {
    key: "hitRadius",
    kind: "number",
    label: "Radio de colisión",
    help: "Más chico que el dibujo a propósito: rozar un tubo perdona y se siente justo.",
    group: "Vuelo",
    min: 6,
    max: 26,
    step: 1,
    unit: "px",
    default: 14,
  },

  /* --- Obstáculos ---------------------------------------------------- */
  {
    key: "pipeGap",
    kind: "number",
    label: "Hueco del tubo",
    help: "Alto libre entre el tubo de arriba y el de abajo al empezar.",
    group: "Obstáculos",
    min: 110,
    max: 320,
    step: 5,
    unit: "px",
    default: 190,
  },
  {
    key: "gapShrink",
    kind: "number",
    label: "Cierre por tubo",
    help: "Cuánto se achica el hueco con cada tubo generado. La dificultad sube sola.",
    group: "Obstáculos",
    min: 0,
    max: 8,
    step: 0.5,
    unit: "px",
    default: 1.5,
  },
  {
    key: "minGap",
    kind: "number",
    label: "Hueco mínimo",
    help: "Piso del cierre: por debajo de esto el juego deja de ser jugable.",
    group: "Obstáculos",
    min: 90,
    max: 240,
    step: 5,
    unit: "px",
    default: 130,
  },
  {
    key: "pipeSpacing",
    kind: "number",
    label: "Separación entre tubos",
    help: "Distancia horizontal entre un tubo y el siguiente.",
    group: "Obstáculos",
    min: 160,
    max: 460,
    step: 10,
    unit: "px",
    default: 260,
  },
  {
    key: "pipeWidth",
    kind: "number",
    label: "Ancho del tubo",
    help: "Grosor de cada obstáculo. Más ancho, menos tiempo para corregir adentro del hueco.",
    group: "Obstáculos",
    min: 36,
    max: 120,
    step: 2,
    unit: "px",
    default: 62,
  },

  /* --- Velocidad ----------------------------------------------------- */
  {
    key: "scrollSpeed",
    kind: "number",
    label: "Velocidad de scroll",
    help: "Velocidad inicial con la que el corredor viene hacia la nave.",
    group: "Velocidad",
    min: 80,
    max: 340,
    step: 5,
    unit: "px/s",
    default: 160,
  },
  {
    key: "speedStep",
    kind: "number",
    label: "Aceleración por tubo",
    help: "Cuánto suma la velocidad cada vez que pasás un tubo.",
    group: "Velocidad",
    min: 0,
    max: 12,
    step: 0.5,
    unit: "px/s",
    default: 2,
  },
  {
    key: "maxSpeed",
    kind: "number",
    label: "Velocidad máxima",
    help: "Tope de la aceleración, para que la partida larga no se vuelva injugable.",
    group: "Velocidad",
    min: 120,
    max: 460,
    step: 10,
    unit: "px/s",
    default: 260,
  },
  {
    key: "difficulty",
    kind: "select",
    label: "Dificultad",
    help: "Ajusta hueco y velocidad de una sola vez, sin tocar el resto de los números.",
    group: "Velocidad",
    options: [
      { value: "relaxed", label: "Relajado" },
      { value: "classic", label: "Clásico" },
      { value: "hard", label: "Exigente" },
    ],
    default: "classic",
  },

  /* --- Puntaje ------------------------------------------------------- */
  {
    key: "pointsPerPipe",
    kind: "number",
    label: "Puntos por tubo",
    help: "Lo que suma cada tubo pasado, sin importar por dónde.",
    group: "Puntaje",
    min: 0,
    max: 500,
    step: 10,
    default: 100,
  },
  {
    key: "perfectBonus",
    kind: "number",
    label: "Bono por centrar",
    help: "Extra al pasar por el centro del hueco. Premia jugar bien, no sólo aguantar.",
    group: "Puntaje",
    min: 0,
    max: 300,
    step: 5,
    default: 25,
  },
  {
    key: "perfectZone",
    kind: "number",
    label: "Zona premiada",
    help: "Porción central del hueco que cuenta como paso perfecto.",
    group: "Puntaje",
    min: 10,
    max: 80,
    step: 5,
    unit: "%",
    default: 30,
  },
  {
    key: "timeBonus",
    kind: "toggle",
    label: "Bono por aguantar",
    help: "Suma puntos según cuánto de la partida sobreviviste. Sin límite de tiempo no aplica.",
    group: "Puntaje",
    default: true,
  },
  {
    key: "maxTimeBonus",
    kind: "number",
    label: "Bono máximo por tiempo",
    help: "Techo del bono anterior, para que no tape al puntaje por tubos.",
    group: "Puntaje",
    min: 0,
    max: 600,
    step: 10,
    default: 200,
  },

  /* --- Presentación -------------------------------------------------- */
  {
    key: "trail",
    kind: "toggle",
    label: "Estela de la nave",
    help: "Partículas cortas detrás de la nave. Se apagan solas con movimiento reducido.",
    group: "Presentación",
    default: true,
  },
  {
    key: "parallax",
    kind: "toggle",
    label: "Fondo con parallax",
    help: "Dos capas de estrellas a distinta velocidad. Con movimiento reducido quedan quietas.",
    group: "Presentación",
    default: true,
  },

  /* --- Contenido ----------------------------------------------------- */
  {
    key: "instructions",
    kind: "text",
    label: "Instrucción de inicio",
    help: "Una línea, la que se lee antes de jugar. No un tutorial.",
    group: "Contenido",
    maxLength: 120,
    placeholder: "Tocá para volar",
    default: "Tocá la pantalla o apretá espacio para impulsarte. Pasá entre los tubos sin chocar.",
  },
  {
    key: "readyHint",
    kind: "text",
    label: "Aviso antes del primer toque",
    help: "Se muestra con la nave flotando: la gravedad no arranca hasta el primer impulso.",
    group: "Contenido",
    maxLength: 60,
    placeholder: "Tocá para volar",
    default: "Tocá para volar",
  },
  {
    key: "loseMessages",
    kind: "words",
    label: "Frases al perder",
    help: "Se elige una según cuántos tubos pasaste. Siempre la misma para el mismo resultado.",
    group: "Contenido",
    itemLabel: "Frase",
    min: 1,
    max: 12,
    default: [
      "Se apagó el motor. De nuevo.",
      "Casi. El tubo estaba justo ahí.",
      "Buen vuelo, mejor caída.",
      "La gravedad sigue invicta.",
      "Un toque más y llegabas.",
    ],
  },
];
