import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Supernova Futbol.
 *
 * Los defaults son los que salieron de jugar la cancha, no numeros redondos.
 * Dos decisiones que conviene entender antes de tocar el panel:
 *
 * - **El rozamiento se expresa como "cuanto pierde por segundo"**, no como el
 *   factor por cuadro que usa la formula. Un administrador entiende "pierde el
 *   91 % de su velocidad por segundo"; nadie entiende 0,98013 por paso. La
 *   conversion la hace `createFutbolRules`, que es donde se sabe cual es el
 *   paso de simulacion.
 * - **La pelota tiene que perder MUCHO menos que un jugador.** Es lo unico que
 *   hace que un pase llegue: si los dos frenan igual, la pelota se muere a dos
 *   metros y el partido se vuelve un amontonamiento.
 */
export const futbolSettings: SettingsSchema = [
  {
    kind: "number",
    key: "fieldWidth",
    label: "Ancho de la cancha",
    group: "Cancha",
    unit: "u",
    min: 1200,
    max: 1900,
    step: 20,
    default: 1600,
    help: "El largo del campo. Más ancha premia el pase y castiga al que corre solo. El tope es 1900 porque la cuantización de la red cubre hasta 2048 unidades y detrás de cada arco hay 70 más.",
  },
  {
    kind: "number",
    key: "fieldHeight",
    label: "Alto de la cancha",
    group: "Cancha",
    unit: "u",
    min: 700,
    max: 1100,
    step: 20,
    default: 900,
    help: "Con 1600 × 900 la cancha entra completa en una pantalla 16:9 sin cámara.",
  },
  {
    kind: "number",
    key: "goalWidth",
    label: "Ancho del arco",
    group: "Cancha",
    unit: "u",
    min: 140,
    max: 420,
    step: 10,
    default: 250,
    help: "Medido entre postes. Debajo de 180 los partidos terminan 0 a 0.",
  },

  {
    kind: "number",
    key: "playerRadius",
    label: "Radio del jugador",
    group: "Discos",
    unit: "u",
    min: 18,
    max: 48,
    step: 1,
    default: 28,
    help: "Discos grandes tapan más y hacen el juego más trabado.",
  },
  {
    kind: "number",
    key: "ballRadius",
    label: "Radio de la pelota",
    group: "Discos",
    unit: "u",
    min: 8,
    max: 28,
    step: 1,
    default: 15,
    help: "Chica se escapa entre los discos; grande se vuelve un globo.",
  },

  {
    kind: "number",
    key: "playerSpeed",
    label: "Velocidad máxima del jugador",
    group: "Jugador",
    unit: "u/s",
    min: 180,
    max: 700,
    step: 10,
    default: 380,
    help: "Techo de carrera. Por encima de la pelota lenta, nadie puede escaparse con ella.",
  },
  {
    kind: "number",
    key: "playerAccel",
    label: "Aceleración del jugador",
    group: "Jugador",
    unit: "u/s²",
    min: 400,
    max: 4000,
    step: 50,
    default: 1900,
    help: "Cuánto tarda en arrancar y en frenar. Alta se siente nerviosa; baja, pesada.",
  },
  {
    kind: "number",
    key: "playerFriction",
    label: "Rozamiento del jugador",
    group: "Jugador",
    unit: "% por s",
    min: 50,
    max: 99,
    step: 1,
    default: 92,
    help: "Velocidad que pierde por segundo si no acelera. Alto = frena solo al soltar.",
  },

  {
    kind: "number",
    key: "ballFriction",
    label: "Rozamiento de la pelota",
    group: "Pelota",
    unit: "% por s",
    min: 10,
    max: 90,
    step: 1,
    default: 42,
    help: "Tiene que ser bastante menor que el del jugador: es lo que hace que el pase llegue.",
  },
  {
    kind: "number",
    key: "kickPower",
    label: "Potencia de la patada",
    group: "Pelota",
    unit: "u/s",
    min: 300,
    max: 1600,
    step: 20,
    default: 900,
    help: "Velocidad que le suma el golpe. Es un golpe, no un arrastre.",
  },
  {
    kind: "number",
    key: "kickReach",
    label: "Alcance de la patada",
    group: "Pelota",
    unit: "u",
    min: 0,
    max: 50,
    step: 2,
    default: 14,
    help: "Cuánto más allá del borde del disco alcanza el golpe. En 0 hay que estar pegado.",
  },
  {
    kind: "number",
    key: "kickCooldown",
    label: "Espera entre patadas",
    group: "Pelota",
    unit: "s",
    min: 0.1,
    max: 1.2,
    step: 0.05,
    default: 0.3,
    help: "Sin espera, quedarse encima de la pelota la dispara sesenta veces por segundo.",
  },
  {
    kind: "number",
    key: "bounce",
    label: "Rebote entre discos",
    group: "Pelota",
    unit: "×",
    min: 0.1,
    max: 1,
    step: 0.05,
    default: 0.55,
    help: "Restitución del choque. En 1 nada pierde energía y el partido se vuelve un flipper.",
  },

  {
    kind: "number",
    key: "goalsToWin",
    label: "Goles para ganar",
    group: "Partido",
    min: 1,
    max: 7,
    step: 1,
    default: 3,
    help: "El partido termina con el primero que llega, aunque quede tiempo.",
  },
  {
    kind: "number",
    key: "matchMinutes",
    label: "Duración del partido",
    group: "Partido",
    unit: "min",
    min: 1,
    max: 6,
    step: 0.5,
    default: 3,
    help: "Lo que llegue antes: los goles o el reloj. Empate al terminar queda empatado.",
  },
  {
    kind: "number",
    key: "celebration",
    label: "Festejo del gol",
    group: "Partido",
    unit: "s",
    min: 0.5,
    max: 4,
    step: 0.5,
    default: 2,
    help: "Sin pausa nadie ve quién hizo el gol.",
  },
  {
    kind: "number",
    key: "kickoff",
    label: "Cuenta del saque",
    group: "Partido",
    unit: "s",
    min: 0.5,
    max: 4,
    step: 0.5,
    default: 2,
    help: "Tiempo para acomodarse después del gol, con la pelota quieta en el centro.",
  },

  {
    kind: "number",
    key: "botSkill",
    label: "Nivel de los bots",
    group: "Bots",
    unit: "%",
    min: 0,
    max: 100,
    step: 5,
    default: 55,
    help: "Puntería y reacción de los que completan los equipos. En 100 no perdonan.",
  },
];
