import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Saltarin (M4).
 *
 * Los defaults son los de games-guide/M4-SALTARIN.md. El grupo "Control" va
 * primero porque es el que se toca en vivo: un juego de inclinacion mal
 * calibrado es insoportable a los diez segundos, y el rango y la zona muerta
 * son los dos numeros que lo arreglan.
 */
export const saltarinSettings: SettingsSchema = [
  /* --- Control ------------------------------------------------------- */
  {
    key: "tiltRange",
    kind: "number",
    label: "Rango de inclinación",
    help: "Grados desde el cero calibrado hasta la velocidad máxima. Más rango, control más suave.",
    group: "Control",
    min: 10,
    max: 45,
    step: 1,
    unit: "°",
    default: 25,
  },
  {
    key: "tiltDeadzone",
    kind: "number",
    label: "Zona muerta",
    help: "Grados que se ignoran alrededor del cero. Es lo que hace que quieto sea quieto.",
    group: "Control",
    min: 0,
    max: 8,
    step: 0.5,
    unit: "°",
    default: 2,
  },
  {
    key: "maxSpeedX",
    kind: "number",
    label: "Velocidad horizontal máxima",
    help: "Velocidad en el extremo del rango. Abajo de 300 no se llega a las plataformas laterales.",
    group: "Control",
    min: 200,
    max: 700,
    step: 10,
    unit: "px/s",
    default: 420,
  },

  /* --- Salto --------------------------------------------------------- */
  {
    key: "gravity",
    kind: "number",
    label: "Gravedad",
    help: "Cuánto tira hacia abajo. Contra 620 de impulso, 1400 da 0,44 s de subida.",
    group: "Salto",
    min: 800,
    max: 2400,
    step: 50,
    unit: "px/s²",
    default: 1400,
  },
  {
    key: "jumpImpulse",
    kind: "number",
    label: "Impulso del rebote",
    help: "Velocidad hacia arriba al tocar una plataforma. Define cuánto se sube por salto.",
    group: "Salto",
    min: 380,
    max: 900,
    step: 10,
    unit: "px/s",
    default: 620,
  },
  {
    key: "boostMultiplier",
    kind: "number",
    label: "Multiplicador de impulso",
    help: "Cuánto más alto salta la plataforma de impulso. En 1 deja de tener sentido buscarla.",
    group: "Salto",
    min: 1,
    max: 3,
    step: 0.1,
    default: 1.8,
  },
  {
    key: "playerRadius",
    kind: "number",
    label: "Radio de la nave",
    help: "Tamaño de la nave y de su caja de contacto.",
    group: "Salto",
    min: 10,
    max: 30,
    step: 1,
    unit: "px",
    default: 18,
  },

  /* --- Plataformas --------------------------------------------------- */
  {
    key: "minGap",
    kind: "number",
    label: "Separación inicial",
    help: "Distancia vertical entre plataformas al empezar.",
    group: "Plataformas",
    min: 50,
    max: 140,
    step: 5,
    unit: "px",
    default: 70,
  },
  {
    key: "maxGap",
    kind: "number",
    label: "Separación máxima",
    help: "Techo de la distancia. Arriba de 150 el salto no llega y la partida se corta sola.",
    group: "Plataformas",
    min: 70,
    max: 180,
    step: 5,
    unit: "px",
    default: 130,
  },
  {
    key: "gapRamp",
    kind: "number",
    label: "Altura de la rampa",
    help: "A qué altura la separación llega al máximo. Es la curva de dificultad entera.",
    group: "Plataformas",
    min: 1000,
    max: 20000,
    step: 500,
    unit: "px",
    default: 6000,
  },
  {
    key: "platformWidth",
    kind: "number",
    label: "Ancho de plataforma",
    group: "Plataformas",
    min: 50,
    max: 140,
    step: 5,
    unit: "px",
    default: 80,
  },
  {
    key: "movingSpeed",
    kind: "number",
    label: "Velocidad de las móviles",
    group: "Plataformas",
    min: 20,
    max: 180,
    step: 5,
    unit: "px/s",
    default: 70,
  },
  {
    key: "movingFrom",
    kind: "number",
    label: "Móviles desde",
    help: "Altura a la que empiezan a aparecer las plataformas que se desplazan.",
    group: "Plataformas",
    min: 0,
    max: 10000,
    step: 250,
    unit: "px",
    default: 1500,
  },
  {
    key: "fragileFrom",
    kind: "number",
    label: "Frágiles desde",
    help: "Las frágiles se rompen y no rebotan: hay que decidir no pisarlas.",
    group: "Plataformas",
    min: 0,
    max: 15000,
    step: 250,
    unit: "px",
    default: 3000,
  },
  {
    key: "boostFrom",
    kind: "number",
    label: "Impulso desde",
    help: "Altura a la que aparecen las plataformas de rebote doble.",
    group: "Plataformas",
    min: 0,
    max: 20000,
    step: 250,
    unit: "px",
    default: 5000,
  },

  /* --- Puntaje ------------------------------------------------------- */
  {
    key: "pixelsPerPoint",
    kind: "number",
    label: "Píxeles por punto",
    help: "Cada cuántos píxeles de altura se suma un punto.",
    group: "Puntaje",
    min: 1,
    max: 50,
    step: 1,
    unit: "px",
    default: 10,
  },
  {
    key: "boostBonus",
    kind: "number",
    label: "Bono por plataforma de impulso",
    help: "Premia buscar los impulsos en vez de ir a lo seguro.",
    group: "Puntaje",
    min: 0,
    max: 200,
    step: 10,
    default: 50,
  },
];
