import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Supernova Pong.
 *
 * Los defaults son los de games-guide/R1-PONG.md. Lo que se toca en el panel
 * se guarda aparte, asi que cambiar un default aca sigue llegando a todos los
 * que no lo tocaron.
 */
export const pongSettings: SettingsSchema = [
  {
    kind: "number",
    key: "ballSpeed",
    label: "Velocidad inicial de la pelota",
    group: "Pelota",
    unit: "u/s",
    min: 400,
    max: 1400,
    step: 20,
    default: 780,
    help: "Sobre una cancha de 1600 × 900. Debajo de 600 el peloteo se hace largo.",
  },
  {
    kind: "number",
    key: "ballAccel",
    label: "Aceleración por rebote",
    group: "Pelota",
    unit: "%",
    min: 0,
    max: 12,
    step: 0.5,
    default: 4,
    help: "Cuánto acelera la pelota cada vez que pega en una paleta.",
  },
  {
    kind: "number",
    key: "maxSpeedFactor",
    label: "Techo de velocidad",
    group: "Pelota",
    unit: "×",
    min: 1,
    max: 4,
    step: 0.1,
    default: 2.2,
    help: "Múltiplo máximo de la velocidad inicial. Sin tope, a los 30 s es injugable.",
  },
  {
    kind: "number",
    key: "serveAngle",
    label: "Ángulo máximo de saque",
    group: "Pelota",
    unit: "°",
    min: 10,
    max: 45,
    step: 5,
    default: 35,
    help: "Medido desde la horizontal. Un saque casi vertical se ve como que el juego se colgó.",
  },

  {
    kind: "number",
    key: "maxBounceAngle",
    label: "Ángulo máximo de rebote",
    group: "Paletas",
    unit: "°",
    min: 30,
    max: 75,
    step: 5,
    default: 60,
    help: "Pegarle con la punta abre hasta este ángulo; al centro sale plano.",
  },
  {
    kind: "number",
    key: "paddleHeight",
    label: "Alto de la paleta",
    group: "Paletas",
    unit: "u",
    min: 90,
    max: 280,
    step: 10,
    default: 170,
    help: "Más corta es más difícil y abre más el ángulo con el mismo error.",
  },
  {
    kind: "number",
    key: "paddleFollow",
    label: "Suavizado de la paleta",
    group: "Paletas",
    min: 0.1,
    max: 1,
    step: 0.05,
    default: 0.35,
    help: "La paleta persigue la posición recibida en vez de saltar. Absorbe el jitter de la red.",
  },

  {
    kind: "number",
    key: "pointsToWin",
    label: "Puntos para ganar",
    group: "Partida",
    min: 3,
    max: 11,
    step: 1,
    default: 7,
    help: "Con diferencia mínima de 2, como en el Pong de siempre.",
  },
  {
    kind: "number",
    key: "hardCap",
    label: "Techo duro de puntos",
    group: "Partida",
    min: 5,
    max: 15,
    step: 1,
    default: 11,
    help: "Corta el partido aunque no haya diferencia de 2, para que entre en la pantalla del tour.",
  },
  {
    kind: "number",
    key: "serveDelay",
    label: "Pausa después del gol",
    group: "Partida",
    unit: "s",
    min: 0.5,
    max: 3,
    step: 0.5,
    default: 1.5,
    help: "Tiempo antes del saque siguiente. Sin pausa, nadie ve quién anotó.",
  },

  {
    kind: "number",
    key: "botError",
    label: "Error del bot",
    group: "Bots",
    unit: "u",
    min: 0,
    max: 320,
    step: 10,
    default: 70,
    help: "Cuánto se desvía el bot del centro de la pelota. En 0 es imbatible.",
  },
  {
    kind: "number",
    key: "botSpeed",
    label: "Velocidad del bot",
    group: "Bots",
    unit: "u/s",
    min: 300,
    max: 2200,
    step: 50,
    default: 950,
    help: "Debajo de la velocidad máxima de la pelota, o nunca llega tarde y no se le puede ganar.",
  },
];
