import type { SettingsSchema } from "@/core/contract/settings";

/** Administrables de Corredor. Los defaults son los de games-guide/M6-CORREDOR.md. */
export const corredorSettings: SettingsSchema = [
  {
    kind: "number",
    key: "baseSpeed",
    label: "Velocidad inicial",
    group: "Ritmo",
    unit: "px/s",
    min: 200,
    max: 500,
    step: 10,
    default: 320,
  },
  {
    kind: "number",
    key: "speedGain",
    label: "Aceleración cada 100 m",
    group: "Ritmo",
    unit: "px/s",
    min: 0,
    max: 30,
    step: 1,
    default: 8,
    help: "En 0 la carrera nunca se pone difícil y las partidas se estiran.",
  },
  {
    kind: "number",
    key: "maxSpeed",
    label: "Velocidad máxima",
    group: "Ritmo",
    unit: "px/s",
    min: 500,
    max: 1200,
    step: 20,
    default: 900,
    help: "Arriba de 900 los tramos dejan de ser superables.",
  },

  {
    kind: "number",
    key: "perMeter",
    label: "Puntos por metro",
    group: "Puntaje",
    min: 1,
    max: 50,
    step: 1,
    default: 10,
  },
  {
    kind: "number",
    key: "perCoin",
    label: "Puntos por moneda",
    group: "Puntaje",
    min: 0,
    max: 100,
    step: 5,
    default: 25,
  },
  {
    kind: "number",
    key: "perGraze",
    label: "Bono por roce",
    group: "Puntaje",
    min: 0,
    max: 60,
    step: 5,
    default: 15,
    help: "Premia jugar al límite en vez de saltar por las dudas con anticipación.",
  },

  {
    kind: "number",
    key: "maxGhosts",
    label: "Siluetas visibles",
    group: "Rendimiento",
    min: 0,
    max: 30,
    step: 1,
    default: 30,
    help: "Es lo primero que se recorta si no se llega a 60 fps: van las más cercanas.",
  },
  {
    kind: "toggle",
    key: "parallax",
    label: "Capas de parallax",
    group: "Rendimiento",
    default: true,
  },
];
