import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Invasores.
 *
 * Los defaults son los de games-guide/R4-INVASORES.md. La horda base es la de
 * la tabla para 1 jugador (3 x 8); el crecimiento por cañon conectado es
 * sublineal y se calcula en `logic.ts`, porque duplicar la horda con el doble
 * de gente la haria mas facil, no mas dificil.
 */
export const invasoresSettings: SettingsSchema = [
  {
    kind: "number",
    key: "baseRows",
    label: "Filas de la horda",
    group: "Horda",
    min: 2,
    max: 5,
    step: 1,
    default: 3,
    help: "Con un solo cañón. Suma una fila cada dos cañones conectados, hasta 5.",
  },
  {
    kind: "number",
    key: "baseCols",
    label: "Columnas de la horda",
    group: "Horda",
    min: 6,
    max: 11,
    step: 1,
    default: 8,
    help: "Con un solo cañón. Suma una columna por cañón conectado, hasta 11.",
  },
  {
    kind: "number",
    key: "marchSpeed",
    label: "Velocidad de la horda",
    group: "Horda",
    unit: "u/s",
    min: 40,
    max: 300,
    step: 5,
    default: 95,
    help: "Sobre un campo de 1600 × 900, con la horda completa y en la primera oleada.",
  },
  {
    kind: "number",
    key: "accelFactor",
    label: "Aceleración por bajas",
    group: "Horda",
    unit: "×",
    min: 0,
    max: 5,
    step: 0.1,
    default: 2.2,
    help: "velocidad = base × (1 + (1 − vivos/total) × esto). El último invasor va 3,2× más rápido.",
  },
  {
    kind: "number",
    key: "stepDown",
    label: "Escalón al tocar el borde",
    group: "Horda",
    unit: "u",
    min: 8,
    max: 60,
    step: 2,
    default: 22,
    help: "Cuánto baja la horda cada vez que rebota contra un costado.",
  },
  {
    kind: "number",
    key: "hordeFireRate",
    label: "Cadencia de la horda",
    group: "Horda",
    unit: "disp/s",
    min: 0.2,
    max: 6,
    step: 0.1,
    default: 1.1,
    help: "Bombas por segundo en la primera oleada. Quién dispara sale del PRNG sembrado.",
  },

  {
    kind: "number",
    key: "fireCooldown",
    label: "Cadencia del cañón",
    group: "Cañones",
    unit: "s",
    min: 0.1,
    max: 1.5,
    step: 0.05,
    default: 0.32,
    help: "Además hay un solo proyectil propio en vuelo: sin eso, cuatro cañones tapan la pantalla.",
  },
  {
    kind: "number",
    key: "bulletSpeed",
    label: "Velocidad del disparo",
    group: "Cañones",
    unit: "u/s",
    min: 400,
    max: 1600,
    step: 50,
    default: 900,
    help: "Los proyectiles son lentos a propósito: entran en un paso de 1/60 sin barrido.",
  },
  {
    kind: "number",
    key: "bombSpeed",
    label: "Velocidad de las bombas",
    group: "Cañones",
    unit: "u/s",
    min: 150,
    max: 900,
    step: 25,
    default: 340,
    help: "Bajar esto es la forma más directa de hacer la partida más indulgente.",
  },
  {
    kind: "number",
    key: "cannonFollow",
    label: "Suavizado del cañón",
    group: "Cañones",
    min: 0.1,
    max: 1,
    step: 0.05,
    default: 0.45,
    help: "El cañón persigue la posición recibida en vez de saltar. Absorbe el jitter de la red.",
  },

  {
    kind: "number",
    key: "lives",
    label: "Vidas compartidas",
    group: "Partida",
    min: 1,
    max: 9,
    step: 1,
    default: 3,
    help: "Son de todos: un cañón alcanzado le cuesta una vida a la sala entera.",
  },
  {
    kind: "number",
    key: "regroupPause",
    label: "Pausa al perder una vida",
    group: "Partida",
    unit: "s",
    min: 0.5,
    max: 4,
    step: 0.5,
    default: 1.5,
    help: "Tiempo para reagruparse. Sin pausa, la segunda vida se pierde antes de entender la primera.",
  },
  {
    kind: "number",
    key: "wavePause",
    label: "Cartel entre oleadas",
    group: "Partida",
    unit: "s",
    min: 1,
    max: 6,
    step: 0.5,
    default: 3,
    help: "Muestra el número de oleada y los puntajes de todos.",
  },
  {
    kind: "number",
    key: "waveSpeedGain",
    label: "Aceleración por oleada",
    group: "Partida",
    unit: "%",
    min: 0,
    max: 40,
    step: 1,
    default: 12,
    help: "Cuánto más rápida arranca cada oleada nueva. Las oleadas son infinitas.",
  },
  {
    kind: "number",
    key: "waveDrop",
    label: "Descenso por oleada",
    group: "Partida",
    unit: "u",
    min: 0,
    max: 60,
    step: 5,
    default: 24,
    help: "Cada oleada empieza más abajo, hasta un tope. Es lo que hace que alguna vez se pierda.",
  },

  {
    kind: "number",
    key: "pointsPerInvader",
    label: "Puntos por invasor",
    group: "Puntos",
    min: 10,
    max: 400,
    step: 10,
    default: 100,
    help: "Individuales: los cobra quien derribó.",
  },
  {
    kind: "number",
    key: "accuracyBonus",
    label: "Bono máximo por precisión",
    group: "Puntos",
    min: 0,
    max: 1200,
    step: 50,
    default: 500,
    help: "aciertos / disparos × esto. Evita la estrategia de disparar sin mirar.",
  },
  {
    kind: "number",
    key: "pointsPerWave",
    label: "Puntos por oleada superada",
    group: "Puntos",
    min: 0,
    max: 900,
    step: 50,
    default: 300,
    help: "Idéntico para todos los conectados, incluido el que jugó peor: es cooperativo.",
  },

  {
    kind: "number",
    key: "botSpeed",
    label: "Velocidad del bot",
    group: "Bots",
    unit: "u/s",
    min: 150,
    max: 1400,
    step: 50,
    default: 620,
    help: "Los asientos vacíos los juega un bot, para que la sala se pueda probar en solitario.",
  },
  {
    kind: "number",
    key: "botAim",
    label: "Error de puntería del bot",
    group: "Bots",
    unit: "u",
    min: 0,
    max: 220,
    step: 10,
    default: 60,
    help: "Cuánto se desvía del centro del invasor al que apunta. En 0 no falla nunca.",
  },
  {
    kind: "toggle",
    key: "botDodge",
    label: "El bot esquiva bombas",
    group: "Bots",
    default: true,
    help: "Apagado, el bot gasta vidas compartidas y la sala lo sufre.",
  },
];
