import type { SettingsSchema } from "@/core/contract/settings";

/**
 * Administrables de Rompeladrillos.
 *
 * Los defaults son los de games-guide/R5-ROMPELADRILLOS.md. Las dos perillas
 * que cambian el juego de verdad son `segmentWidth` y `maxSeparation`: la
 * primera decide cuanto cubre cada mitad, la segunda cuanto se pueden alejar
 * antes de que la correa los frene. Tocar cualquiera de las dos convierte esto
 * en otro juego, asi que salen documentadas y no escondidas en el codigo.
 */
export const rompeladrillosSettings: SettingsSchema = [
  {
    kind: "number",
    key: "ballSpeed",
    label: "Velocidad inicial de la pelota",
    group: "Pelota",
    unit: "u/s",
    min: 240,
    max: 900,
    step: 20,
    default: 420,
    help: "Sobre una cancha de 1600 × 900. Debajo de 320 la coordinación deja de exigir nada.",
  },
  {
    kind: "number",
    key: "ballAccel",
    label: "Aceleración por rebote",
    group: "Pelota",
    unit: "%",
    min: 0,
    max: 10,
    step: 0.5,
    default: 3,
    help: "Cuánto acelera la pelota cada vez que pega en un segmento o en un ladrillo.",
  },
  {
    kind: "number",
    key: "maxSpeedFactor",
    label: "Techo de velocidad",
    group: "Pelota",
    unit: "×",
    min: 1,
    max: 3,
    step: 0.1,
    default: 2,
    help: "Múltiplo máximo de la velocidad inicial. Sin tope, al tercer nivel es injugable.",
  },
  {
    kind: "number",
    key: "maxBounceAngle",
    label: "Ángulo máximo de rebote",
    group: "Pelota",
    unit: "°",
    min: 30,
    max: 75,
    step: 5,
    default: 60,
    help: "Medido desde la vertical. Pegarle con la punta abre hasta este ángulo; al centro sale recta.",
  },

  {
    kind: "number",
    key: "segmentWidth",
    label: "Ancho de cada segmento",
    group: "Paleta partida",
    unit: "u",
    min: 60,
    max: 200,
    step: 10,
    default: 110,
    help: "Juntos forman una paleta sólida del doble. La cápsula Ancho le suma 40 a los dos.",
  },
  {
    kind: "number",
    key: "minGap",
    label: "Separación mínima entre segmentos",
    group: "Paleta partida",
    unit: "u",
    min: 0,
    max: 60,
    step: 5,
    default: 0,
    help: "En 0 se pueden tocar y no queda hueco. Arriba de 0 siempre hay por dónde perderla.",
  },
  {
    kind: "number",
    key: "maxSeparation",
    label: "Separación máxima entre centros",
    group: "Paleta partida",
    unit: "u",
    min: 200,
    max: 900,
    step: 20,
    default: 420,
    help: "La correa entre las dos mitades. Es lo que obliga a negociar en vez de tener media cancha cada uno.",
  },
  {
    kind: "number",
    key: "segmentFollow",
    label: "Suavizado del segmento",
    group: "Paleta partida",
    min: 0.15,
    max: 1,
    step: 0.05,
    default: 0.45,
    help: "El segmento persigue la posición recibida en vez de saltar. Absorbe el jitter de la red.",
  },

  {
    kind: "number",
    key: "brickRows",
    label: "Filas de ladrillos",
    group: "Ladrillos",
    min: 4,
    max: 10,
    step: 1,
    default: 8,
    help: "Sobre 14 columnas fijas. Más filas alargan el nivel, no lo hacen más difícil.",
  },
  {
    kind: "number",
    key: "capsuleChance",
    label: "Ladrillos con cápsula",
    group: "Ladrillos",
    unit: "%",
    min: 0,
    max: 40,
    step: 1,
    default: 12,
    help: "Con la misma semilla caen siempre de los mismos ladrillos. En 0 no hay cápsulas.",
  },
  {
    kind: "number",
    key: "capsuleSpeed",
    label: "Caída de la cápsula",
    group: "Ladrillos",
    unit: "u/s",
    min: 100,
    max: 400,
    step: 10,
    default: 210,
    help: "Muy rápida obliga a abandonar la pelota para ir a buscarla, y eso cuesta una vida.",
  },

  {
    kind: "number",
    key: "lives",
    label: "Vidas compartidas",
    group: "Partida",
    min: 1,
    max: 6,
    step: 1,
    default: 3,
    help: "Son de los dos: no hay vidas propias. Perder una es culpa compartida.",
  },
  {
    kind: "number",
    key: "loseDelay",
    label: "Pausa al perder una vida",
    group: "Partida",
    unit: "s",
    min: 0.5,
    max: 3,
    step: 0.5,
    default: 1.5,
    help: "Sin pausa nadie entiende qué pasó y la siguiente se pierde igual.",
  },

  {
    kind: "number",
    key: "botSpeed",
    label: "Velocidad del bot",
    group: "Bots",
    unit: "u/s",
    min: 200,
    max: 1600,
    step: 50,
    default: 720,
    help: "Los asientos vacíos los juega un bot para poder probar en solitario. Muy rápido no falla nunca.",
  },
  {
    kind: "number",
    key: "botError",
    label: "Error del bot",
    group: "Bots",
    unit: "u",
    min: 0,
    max: 260,
    step: 10,
    default: 60,
    help: "Cuánto se desvía de donde debería estar. En 0 la pelota no se cae jamás.",
  },
];
