import type { SettingsSchema } from "@/core/contract/settings";
import { LEVEL_RECORDS } from "./levels";

/**
 * Administrables de Catapulta.
 *
 * Los defaults son los de games-guide/M2-CATAPULTA.md. Los cinco niveles no son
 * constantes escondidas en el componente: entran como contenido editable, asi
 * que se puede armar un nivel nuevo sin tocar codigo.
 */
export const catapultaSettings: SettingsSchema = [
  {
    kind: "number",
    key: "shotsPerLevel",
    label: "Tiros por nivel",
    group: "Partida",
    unit: "tiros",
    min: 1,
    max: 6,
    step: 1,
    default: 3,
    help: "Se usa en los niveles que no declaran los suyos. Con más de cuatro deja de ser puntería.",
  },
  {
    kind: "number",
    key: "settleMs",
    label: "Espera hasta que se aquiete",
    group: "Partida",
    unit: "ms",
    min: 1500,
    max: 8000,
    step: 250,
    default: 5000,
    help: "Tope de espera después del tiro. Un bloque puede caer tres segundos tarde y cambiar el resultado.",
  },

  {
    kind: "number",
    key: "gravity",
    label: "Gravedad",
    group: "Física",
    unit: "px/s²",
    min: 400,
    max: 1600,
    step: 20,
    default: 980,
    help: "Tira hacia abajo. Más baja alarga la parábola y hace el juego más lento.",
  },
  {
    kind: "number",
    key: "maxLaunchSpeed",
    label: "Fuerza máxima del lanzamiento",
    group: "Física",
    unit: "px/s",
    min: 600,
    max: 2000,
    step: 50,
    default: 1200,
    help: "Velocidad de salida con la banda estirada del todo.",
  },

  {
    kind: "number",
    key: "woodStrength",
    label: "Resistencia de la madera",
    group: "Resistencia",
    min: 100,
    max: 2000,
    step: 25,
    default: 700,
    help: "Impulso de impacto que aguanta un bloque de madera antes de romperse.",
  },
  {
    kind: "number",
    key: "stoneStrength",
    label: "Resistencia de la piedra",
    group: "Resistencia",
    min: 400,
    max: 6000,
    step: 50,
    default: 2400,
    help: "La piedra está para no romperse de frente: obliga a buscar otro ángulo.",
  },
  {
    kind: "number",
    key: "targetStrength",
    label: "Resistencia del objetivo",
    group: "Resistencia",
    min: 40,
    max: 1000,
    step: 10,
    default: 140,
    help: "Los objetivos aguantan menos que la estructura que los protege.",
  },

  {
    kind: "number",
    key: "pointsPerTarget",
    label: "Puntos por objetivo",
    group: "Puntaje",
    min: 50,
    max: 2000,
    step: 50,
    default: 500,
  },
  {
    kind: "number",
    key: "pointsPerBlock",
    label: "Puntos por bloque derribado",
    group: "Puntaje",
    min: 0,
    max: 200,
    step: 5,
    default: 25,
    help: "Daño colateral. Suma, pero nunca alcanza para ganar el nivel.",
  },
  {
    kind: "number",
    key: "pointsPerSpareShot",
    label: "Puntos por tiro sin usar",
    group: "Puntaje",
    min: 0,
    max: 1000,
    step: 50,
    default: 300,
    help: "Es lo que hace al juego de puntería y no de insistencia: resolver de un tiro vale más.",
  },

  {
    kind: "records",
    key: "levels",
    label: "Niveles",
    group: "Contenido",
    titleKey: "name",
    min: 1,
    max: 10,
    help: "Cada bloque es «x,y,ancho,alto,material» y cada objetivo «x,y», con el centro en píxeles del mundo de 1600×900.",
    fields: [
      { kind: "text", key: "name", label: "Nombre", maxLength: 40, default: "" },
      {
        kind: "number",
        key: "shots",
        label: "Tiros de este nivel",
        min: 0,
        max: 6,
        step: 1,
        default: 0,
        help: "0 usa el valor general.",
      },
      {
        kind: "words",
        key: "blocks",
        label: "Bloques",
        itemLabel: "Bloque",
        min: 0,
        max: 48,
        default: [],
      },
      {
        kind: "words",
        key: "targets",
        label: "Objetivos",
        itemLabel: "Objetivo",
        min: 1,
        max: 8,
        default: [],
      },
    ],
    default: LEVEL_RECORDS,
  },
];
